MolDyn_NVE.exe: MolDyn_NVE.cpp
	g++ MolDyn_NVE.cpp -o MolDyn_NVE.exe

run:
	./MolDyn_NVE.exe

clean:
	./clean.sh

runw/restart:
	./restart.sh

runsolid:
	./solid.sh

runliquid:
	./liquid.sh

rungas:
	./gas.sh
